### ISSUE TITLE
How to modify HTML/CSS output

### ISSUE THREAD

**Issue by ghost** [Swagger2Markup/swagger2markup-gradle-project-template#2]
Hi!  I am trying to use asciidoctor templates as outlined in the following:

https://github.com/asciidoctor/asciidoctor/issues/2273

However, after copying templates out of https://github.com/asciidoctor/asciidoctor-backends, templates don't seem to work.  What can I do to resolve this?

**Comment by RobWin** [comment]
Hi,
I never tried it. Sry, I can't answer you that question.
